### ISSUE TITLE
Reports ENOTFOUND for valid CoAP URI

### ISSUE THREAD

**Issue by sjlongland** [federicorossifr/node-coap-browser#1]
On the command line, I can do the following:

```
$ coap-client coap://[fdde:ad00:beef:0:0:ff:fe00:fc00]/t
v:1 t:CON c:GET i:f90f {} [ ]
AResponse
```

Paste the exact same URI into `node-coap-browser` (running in NodeJS 12 on Linux, no Docker involved) and I get this:

![node-coap-browser-enotfound](https://user-images.githubusercontent.com/1710526/70682020-3297fa80-1ce9-11ea-9e6f-0ab4f512dd8e.png)

`tcpdump` on the relevant network interface shows no traffic.  Why is it lying to me about not finding the resource when it didn't even try?

**Comment by federicorossifr** [comment]
Hi Stuart,I'll check it during the day. Have you tried to insert the address without the leading "coap://" or even to remove also the square brackets?
-------- Messaggio originale --------Da: Stuart Longland <notifications@github.com> Data: 12/12/19  05:12  (GMT+01:00) A: federicorossifr/node-coap-browser <node-coap-browser@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Oggetto: [federicorossifr/node-coap-browser] Reports ENOTFOUND for valid CoAP
  URI (#1) On the command line, I can do the following:
$ coap-client coap://[fdde:ad00:beef:0:0:ff:fe00:fc00]/t
v:1 t:CON c:GET i:f90f {} [ ]
AResponse

Paste the exact same URI into node-coap-browser (running in NodeJS 12 on Linux, no Docker involved) and I get this:

tcpdump on the relevant network interface shows no traffic.  Why is it lying to me about not finding the resource when it didn't even try?

**Comment by sjlongland** [comment]
On 12/12/19 4:44 pm, Federico Rossi wrote:
> Hi Stuart,I'll check it during the day. Have you tried to insert the address without the leading "coap://" or even to remove also the square brackets?

I did, and also without the square brackets (doing either of which
violates RFC 3986).

Doing this it didn't seem to recognise the address at all, possibly
because without the coap:// prefix it can't know whether it should be
using clear-text UDP CoAP on port 5683, dTLS-secured CoAP on port 5682,
CoAP over TCP or any other CoAP transport.

Also, when removing the square brackets, the IPv6 address will look like
a host-name and port number -- parsing of which will fail since there's
more than one colon to split on and consist of hexadecimal digits
instead of decimal.

For this reason, *both* should be specified -- assuming things is asking
for trouble.
